/* header.h.  Generated by configure.  */
/* header.h.in.  Generated from configure.ac by autoheader.  */

/* SDL_Mixer support */
#define AUDIO_SDL 1

/* Include pthread support for binary relocation? */
#define BR_PTHREAD 1

/* Use binary relocation? */
#undef ENABLE_BINRELOC

/* Define to 1 if you have the <inttypes.h> header file. */
#undef HAVE_INTTYPES_H

/* Define to 1 if you have the `GL' library (-lGL). */
#define HAVE_LIBGL 1

/* Define to 1 if you have the `GLU' library (-lGLU). */
#define HAVE_LIBGLU 1

/* Define to 1 if you have the `png' library (-lpng). */
#define HAVE_LIBPNG 1

/* Define to 1 if you have the `pthread' library (-lpthread). */
#define HAVE_LIBPTHREAD 1

/* Define to 1 if you have the `SDL_image' library (-lSDL_image). */
#define HAVE_LIBSDL_IMAGE 1

/* Define to 1 if you have the `SDL_net' library (-lSDL_net). */
#define HAVE_LIBSDL_NET 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#undef HAVE_STDINT_H

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#undef HAVE_STRINGS_H

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#undef HAVE_UNISTD_H

/* Name of package */
#define PACKAGE "opencity"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "OpenCity"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "OpenCity 0.0.5stable"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "opencity"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.0.5stable"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.0.5stable"
